---
expected_ospf_neighbors_ips:
  - 1.1.1.1
  - 6.6.6.6

bgp_bgp:
  local_asn: 65510
  bgp_peers:
    - ip: 1.1.1.1
      remote_as: 65510
      update_source: Loopback0
    - ip: 3.3.3.3
      remote_as: 65510
      update_source: Loopback0
address_families:
  - name: ipv4 unicast
    redistribute_ospf: true
    redistribute_ospf_process: 100
    neighbors:
      - ip: 1.1.1.1
        activate: true
      - ip: 3.3.3.3
        activate: true
