---
expected_ospf_neighbors_ips:
  - 5.5.5.5
  - 3.3.3.3


vpn_config:
  vpn_name: "vpn_r3"
  tunnel_ip: "192.168.2.2"
  peer_ip: "1.1.1.1"  # IP address of the remote VPN peer
  local_ip: "192.168.2.2"  # Local IP address for the VPN
  pre_shared_key: "super_secret_key"  # Pre-shared key for authentication
  transform_set: "esp-aes"  # Transform set name
  group_policy: "default_group_policy"  # Group policy name
  lifetime: 3600  # Lifetime of the IPsec SA