---
galaxy_info:
  author: your_name
  description: Ansible role to configure IPsec VPN on Cisco devices.
  company: your_company
  license: license_name
  min_ansible_version: 2.9
  platforms:
    - name: Cisco IOS
      versions:
        - all

dependencies: []