---
- name: Verify BGP Configuration
  hosts: routers
  gather_facts: no

  tasks:
    - name: Show BGP Neighbors
      cisco.ios.ios_command:
         commands:
          - show ip bgp summary
      register: bgp_output

    - name: Parse neighbor IP addresses from BGP output lines
      set_fact:
        actual_bgp_neighbor_ips: []

    - name: Extract BGP neighbor IPs from CLI output
      set_fact:
        actual_bgp_neighbor_ips: "{{ actual_bgp_neighbor_ips + [item.split()[0]] }}"
      loop: "{{ bgp_output.stdout_lines | default([]) | flatten }}"
      when: item | length > 0 and item.split()[0] | regex_search('^\\d+\\.\\d+\\.\\d+\\.\\d+$')


    - name: Show unexpected BGP neighbors with friendly messages
      debug:
        msg: "{{ item }} is present on the live device, but isn't defined in expected neighbors."
      loop: "{{ actual_bgp_neighbor_ips | difference(expected_bgp_neighbors_ips) }}"
      when: (actual_bgp_neighbor_ips | difference(expected_bgp_neighbors_ips)) | length > 0

    - name: Assert BGP neighbor IPs match expected list exactly
      assert:
        that:
          - "(expected_bgp_neighbors_ips | difference(actual_bgp_neighbor_ips)) | length == 0"
          - "(actual_bgp_neighbor_ips | difference(expected_bgp_neighbors_ips)) | length == 0"
        fail_msg: | 
          BGP neighbor IP mismatch on {{ inventory_hostname }}.
          Expected: {{ expected_bgp_neighbors_ips | to_nice_yaml(indent=2) }}
          Found: {{ actual_bgp_neighbor_ips | to_nice_yaml(indent=2) }}
          Missing: {{ expected_bgp_neighbors_ips | difference(actual_bgp_neighbor_ips) | to_nice_yaml(indent=2) }}
          Unexpected: {{ actual_bgp_neighbor_ips | difference(expected_bgp_neighbors_ips) | to_nice_yaml(indent=2) }}
        success_msg: "All defined BGP neighbors exist and no unexpected neighbors were found"