- name: Deploy BGP Configuration
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Set BGP neighbor configuration
      ansible.builtin.set_fact:
        bgp_neighbors: "{{ lookup('template', '../templates/bgp_neighbors.j2') | from_yaml }}"

    - name: Replaces device configuration of listed global BGP with provided configuration
      cisco.ios.ios_bgp_global:
        config:
          as_number: "{{ bgp_bgp.local_asn }}"
          bgp:
            router_id:
              address: "{{ bgp_bgp.router_id }}"
            default:
              ipv4_unicast: true
            log_neighbor_changes: true
          neighbors: "{{ bgp_neighbors }}"
