---
- name: Pull current config from devices
  hosts: all
  gather_facts: no
  tasks:
    - name: Get running config
      ios_command:
        commands: show running-config
      register: output

    - name: Save config to file
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "./configs/{{ inventory_hostname }}.cfg"
